'use strict';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clone=o=>JSON.parse(JSON.stringify(o));
const fmt=(n,d=4)=>{ if(!Number.isFinite(Number(n))) return '—'; const x=Number(n); if(Math.abs(x)!==0&&(Math.abs(x)>=1e6||Math.abs(x)<1e-4)) return x.toExponential(4); return x.toLocaleString('en-US',{maximumFractionDigits:d}); };
const zeros=(r,c)=>Array.from({length:r},()=>Array(c).fill(0));
const vectorZeros=n=>Array(n).fill(0);
const maxAbs=a=>Math.max(0,...a.flat(Infinity).map(x=>Math.abs(Number(x)||0));

const EX1={name:'Example 1',lengthUnit:'cm',forceUnit:'kgf',scale:500,nodes:[['A',0,0],['B',300,0],['C',600,0],['D',150,100],['E',300,200],['F',450,100]],bars:[['A','B',25,2e6],['B','C',25,2e6],['B','D',25,2e6],['B','F',25,2e6],['B','E',25,2e6],['A','D',25,2e6],['D','E',25,2e6],['E','F',25,2e6],['F','C',25,2e6]],loads:[['D',2000,-1000],['E',2000,-1000],['F',2000,-1000]],supports:[['A',true,true],['C',false,true]]};
const EX2={name:'Example 2',lengthUnit:'cm',forceUnit:'kN',scale:500,nodes:[['A',1000,0],['B',3400,2000],['C',975,250],['D',3400,1500],['E',1050,500],['F',900,1000],['G',3100,1750],['H',850,1500],['I',1150,1500],['J',0,2000],['K',400,2000],['L',400,2200],['M',800,2000],['N',800,2400],['O',1200,2000],['P',1200,2400],['Q',1600,2000],['R',1600,2400],['S',2000,2000],['T',2000,2400],['U',2400,2000],['V',2400,2400],['W',2800,2000],['X',2800,2400],['Y',3100,2000],['Z',3100,2200],['1',950,500],['2',1100,1000]],bars:[['A','C',625,21000],['A','E',625,21000],['C','E',625,21000],['C','1',625,21000],['1','E',625,21000],['1','F',625,21000],['1','2',625,21000],['E','F',625,21000],['E','2',625,21000],['F','2',625,21000],['F','H',625,21000],['F','I',625,21000],['2','H',625,21000],['2','I',625,21000],['H','I',625,21000],['H','M',625,21000],['H','O',625,21000],['I','O',625,21000],['J','K',625,21000],['K','M',625,21000],['M','O',625,21000],['O','Q',625,21000],['Q','S',625,21000],['S','U',625,21000],['U','W',625,21000],['W','Y',625,21000],['Y','B',625,21000],['W','G',625,21000],['G','B',625,21000],['G','D',625,21000],['D','B',625,21000],['J','L',625,21000],['K','L',625,21000],['L','N',625,21000],['L','M',625,21000],['K','N',625,21000],['M','N',625,21000],['M','P',625,21000],['N','P',625,21000],['O','P',625,21000],['O','R',625,21000],['Q','P',625,21000],['Q','R',625,21000],['P','R',625,21000],['S','R',625,21000],['S','T',625,21000],['T','R',625,21000],['S','V',625,21000],['U','V',625,21000],['T','V',625,21000],['U','X',625,21000],['W','V',625,21000],['W','X',625,21000],['V','X',625,21000],['W','Z',625,21000],['X','Z',625,21000],['Y','Z',625,21000],['Z','B',625,21000]],loads:[['J',8,-160],['F',22,0],['S',0,-510]],supports:[['A',true,true],['D',false,true]]};

let model=clone(EX1), result=null, activeResultTab='summary';

function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
async function hash(s){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function initAuth(){const session=localStorage.getItem('tocascame_session'); if(session) showApp();$$('[data-auth-tab]').forEach(b=>b.onclick=()=>{$$('[data-auth-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#loginForm').classList.toggle('hidden',b.dataset.authTab!=='login');$('#registerForm').classList.toggle('hidden',b.dataset.authTab!=='register')});$('#registerForm').onsubmit=async e=>{e.preventDefault();const email=$('#registerEmail').value.trim().toLowerCase(),name=$('#registerName').value.trim(),password=await hash($('#registerPassword').value);localStorage.setItem('tocascame_user_'+email,JSON.stringify({name,email,password}));localStorage.setItem('tocascame_session',email);showApp();toast('Cuenta local creada')};$('#loginForm').onsubmit=async e=>{e.preventDefault();const email=$('#loginEmail').value.trim().toLowerCase(),u=JSON.parse(localStorage.getItem('tocascame_user_'+email)||'null');if(!u||u.password!==await hash($('#loginPassword').value)) return toast('Correo o contraseña incorrectos');localStorage.setItem('tocascame_session',email);showApp();toast('Bienvenido a TOCAScAmE')};$('#logoutBtn').onclick=()=>{localStorage.removeItem('tocascame_session');location.reload()}}
function showApp(){$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');renderInputs();draw();}

function renderInputs(){ $('#lengthUnit').value=model.lengthUnit;$('#forceUnit').value=model.forceUnit;$('#deformScale').value=model.scale;renderRows();updateStats(); }
function renderRows(){
 const tbody=(id,html)=>$(id).innerHTML=html;
 tbody('#nodesBody',model.nodes.map((n,i)=>`<tr><td><input data-kind="node" data-i="${i}" data-k="0" value="${n[0]}"></td><td><input type="number" data-kind="node" data-i="${i}" data-k="1" value="${n[1]}"></td><td><input type="number" data-kind="node" data-i="${i}" data-k="2" value="${n[2]}"></td><td><button class="row-del" data-del="node" data-i="${i}">×</button></td></tr>`).join(''));
 tbody('#barsBody',model.bars.map((b,i)=>`<tr><td>${i+1}</td><td><input data-kind="bar" data-i="${i}" data-k="0" value="${b[0]}"></td><td><input data-kind="bar" data-i="${i}" data-k="1" value="${b[1]}"></td><td><input type="number" data-kind="bar" data-i="${i}" data-k="2" value="${b[2]}"></td><td><input type="number" data-kind="bar" data-i="${i}" data-k="3" value="${b[3]}"></td><td><button class="row-del" data-del="bar" data-i="${i}">×</button></td></tr>`).join(''));
 tbody('#loadsBody',model.loads.map((l,i)=>`<tr><td><input data-kind="load" data-i="${i}" data-k="0" value="${l[0]}"></td><td><input type="number" data-kind="load" data-i="${i}" data-k="1" value="${l[1]}"></td><td><input type="number" data-kind="load" data-i="${i}" data-k="2" value="${l[2]}"></td><td><button class="row-del" data-del="load" data-i="${i}">×</button></td></tr>`).join(''));
 tbody('#supportsBody',model.supports.map((s,i)=>`<tr><td><input data-kind="support" data-i="${i}" data-k="0" value="${s[0]}"></td><td><input type="checkbox" data-kind="support" data-i="${i}" data-k="1" ${s[1]?'checked':''}></td><td><input type="checkbox" data-kind="support" data-i="${i}" data-k="2" ${s[2]?'checked':''}></td><td><button class="row-del" data-del="support" data-i="${i}">×</button></td></tr>`).join(''));
 $$('[data-kind]').forEach(el=>el.onchange=()=>{const a=model[el.dataset.kind+'s']||model[el.dataset.kind==='bar'?'bars':el.dataset.kind==='node'?'nodes':el.dataset.kind==='load'?'loads':'supports'];let v=el.type==='checkbox'?el.checked:(el.type==='number'?Number(el.value):el.value.trim());a[+el.dataset.i][+el.dataset.k]=v;result=null;updateStats();draw()});
 $$('[data-del]').forEach(b=>b.onclick=()=>{model[b.dataset.del+'s'].splice(+b.dataset.i,1);result=null;renderRows();updateStats();draw()});
}

function validateModel(m){const names=m.nodes.map(n=>String(n[0]));if(names.length<2)throw Error('Se requieren al menos 2 nodos.');if(new Set(names).size!==names.length)throw Error('Los nombres de nodos no pueden repetirse.');const map=new Set(names);for(const [i,j,A,E] of m.bars){if(!map.has(String(i))||!map.has(String(j)))throw Error(`Barra ${i}-${j}: nodo inexistente.`);if(i===j)throw Error(`Barra ${i}-${j}: nodos iguales.`);if(!(A>0&&E>0))throw Error(`Barra ${i}-${j}: A y E deben ser positivos.`)}for(const [n] of [...m.loads,...m.supports])if(!map.has(String(n)))throw Error(`Nodo ${n} no existe.`);if(!m.supports.some(s=>s[1]||s[2]))throw Error('Define al menos una restricción.');}
function solveLinear(A,b){const n=A.length,M=A.map((r,i)=>[...r,b[i]]);for(let k=0;k<n;k++){let p=k;for(let i=k+1;i<n;i++)if(Math.abs(M[i][k])>Math.abs(M[p][k]))p=i;if(Math.abs(M[p][k])<1e-12*Math.max(1,maxAbs(A)))throw Error('La matriz de rigidez libre es singular o la estructura es inestable. Revisa apoyos, conectividad y mecanismos.');[M[k],M[p]]=[M[p],M[k]];for(let i=k+1;i<n;i++){const f=M[i][k]/M[k][k];for(let j=k;j<=n;j++)M[i][j]-=f*M[k][j]}}const x=Array(n).fill(0);for(let i=n-1;i>=0;i--){let s=M[i][n];for(let j=i+1;j<n;j++)s-=M[i][j]*x[j];x[i]=s/M[i][i]}return x}
function matVec(A,x){return A.map(r=>r.reduce((s,v,i)=>s+v*x[i],0))}
function analyze(m){validateModel(m);const nodeNames=m.nodes.map(n=>String(n[0])),idx=Object.fromEntries(nodeNames.map((n,i)=>[n,i])),coord=Object.fromEntries(m.nodes.map(n=>[String(n[0]),[+n[1],+n[2]]]));const ndof=nodeNames.length*2,K=zeros(ndof,ndof),elements=[];
 m.bars.forEach((b,e)=>{const [ni,nj,A,E]=b.map((x,k)=>k<2?String(x):+x),[xi,yi]=coord[ni],[xj,yj]=coord[nj],dx=xj-xi,dy=yj-yi,L=Math.hypot(dx,dy);if(L<=1e-12)throw Error(`Barra ${ni}-${nj}: longitud nula.`);const c=dx/L,s=dy/L,k=A*E/L;const kl=[[k,-k],[-k,k]],kg=[[c*c,c*s,-c*c,-c*s],[c*s,s*s,-c*s,-s*s],[-c*c,-c*s,c*c,c*s],[-c*s,-s*s,c*s,s*s]].map(r=>r.map(v=>v*k));const dofs=[2*idx[ni],2*idx[ni]+1,2*idx[nj],2*idx[nj]+1];for(let a=0;a<4;a++)for(let z=0;z<4;z++)K[dofs[a]][dofs[z]]+=kg[a][z];elements.push({id:e+1,ni,nj,A,E,L,c,s,kl,kg,dofs});});
 const F=vectorZeros(ndof),loadDofs=[];m.loads.forEach(([n,fx,fy])=>{const p=idx[String(n)];F[2*p]+=+fx||0;F[2*p+1]+=+fy||0;loadDofs.push(2*p,2*p+1)});const restricted=[];m.supports.forEach(([n,ux,uy])=>{const p=idx[String(n)];if(ux)restricted.push(2*p);if(uy)restricted.push(2*p+1)});const rset=new Set(restricted),free=[...Array(ndof).keys()].filter(i=>!rset.has(i));const Kff=free.map(i=>free.map(j=>K[i][j])),Ff=free.map(i=>F[i]);const uf=solveLinear(Kff,Ff),u=vectorZeros(ndof);free.forEach((d,i)=>u[d]=uf[i]);const Ku=matVec(K,u),R=Ku.map((v,i)=>v-F[i]);elements.forEach(el=>{const ue=el.dofs.map(d=>u[d]);el.strain=(-el.c*ue[0]-el.s*ue[1]+el.c*ue[2]+el.s*ue[3])/el.L;el.stress=el.E*el.strain;el.normal=el.A*el.stress;el.type=el.normal>1e-9?'Tracción':el.normal<-1e-9?'Compresión':'Neutro'});const nodal=nodeNames.map((n,i)=>({node:n,ux:u[2*i],uy:u[2*i+1],fx:F[2*i],fy:F[2*i+1],rx:R[2*i],ry:R[2*i+1]}));return{nodeNames,coord,ndof,K,F,restricted:[...new Set(restricted)].sort((a,b)=>a-b),free,Kff,u,R,elements,nodal,loadDofs:[...new Set(loadDofs)]}}

function calc(){syncMeta();try{result=analyze(model);activeResultTab='summary';renderResults();updateStats();draw();$('#statusText').textContent=`Análisis completado · ${result.ndof} GDL · ${result.elements.length} elementos`;toast('Cálculo completado correctamente')}catch(e){result=null;$('#statusText').textContent='Revisa el modelo';toast(e.message);$('#resultContent').innerHTML=`<div class="empty-state"><strong>Error de análisis:</strong> ${escapeHtml(e.message)}</div>`}}
function syncMeta(){model.lengthUnit=$('#lengthUnit').value.trim()||'u';model.forceUnit=$('#forceUnit').value.trim()||'F';model.scale=Number($('#deformScale').value)||1}
function updateStats(){const n=model.nodes.length,b=model.bars.length;$('#statNodes').textContent=n;$('#statBars').textContent=b;$('#statDofs').textContent=n*2;$('#statDisp').textContent=result?fmt(Math.max(...result.nodal.map(x=>Math.hypot(x.ux,x.uy))),5):'—'}
const escapeHtml=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function table(headers,rows,classes=''){return `<div class="matrix-wrap"><table class="matrix-table ${classes}"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function matrixBlock(title,M,rowLabels=[],colLabels=[]){const hdr=['',...(colLabels.length?colLabels:M[0].map((_,i)=>i))];return `<h4 class="matrix-title">${title}</h4>${table(hdr,M.map((r,i)=>[rowLabels[i]??i,...r.map(v=>fmt(v,4))]))}`}
function renderResults(){if(!result)return;const tabs=[['summary','Resumen'],['elements','Rigidez por elemento'],['dofs','GDL'],['assembly','Ensamblaje K'],['forces','Vector F'],['free','Sistema libre'],['disp','Desplazamientos'],['reactions','Reacciones'],['internal','Esfuerzos internos']];$('#resultTabs').innerHTML=tabs.map(([id,l])=>`<button class="result-tab ${activeResultTab===id?'active':''}" data-rt="${id}">${l}</button>`).join('');$$('[data-rt]').forEach(b=>b.onclick=()=>{activeResultTab=b.dataset.rt;renderResults()});const r=result,du=model.lengthUnit,fu=model.forceUnit;let html='';
 if(activeResultTab==='summary'){const maxD=Math.max(...r.nodal.map(x=>Math.hypot(x.ux,x.uy)));const maxN=Math.max(...r.elements.map(e=>Math.abs(e.normal)));html=`<div class="stats-grid"><article class="stat"><span>GDL libres</span><strong>${r.free.length}</strong></article><article class="stat"><span>GDL restringidos</span><strong>${r.restricted.length}</strong></article><article class="stat"><span>Máx. desplazamiento</span><strong>${fmt(maxD,5)} ${du}</strong></article><article class="stat"><span>Máx. |N|</span><strong>${fmt(maxN,3)} ${fu}</strong></article></div><p>El modelo fue resuelto mediante el <strong>método de rigidez directa</strong>. Usa las pestañas superiores para revisar todo el procedimiento.</p>`}
 if(activeResultTab==='elements'){html=r.elements.map(e=>`<div><h4>Elemento ${e.id}: ${e.ni}–${e.nj} · L=${fmt(e.L,3)} ${du} · c=${fmt(e.c,4)} · s=${fmt(e.s,4)}</h4>${matrixBlock('Matriz de rigidez local kᵉ',e.kl,['uᵢ','uⱼ'],['uᵢ','uⱼ'])}${matrixBlock('Matriz de rigidez global Kᵉ',e.kg,e.dofs.map(x=>'GDL '+x),e.dofs.map(x=>'GDL '+x))}</div>`).join('')}
 if(activeResultTab==='dofs'){html=`<h4>GDL por barra</h4>${table(['Elemento','Barra','GDL'],r.elements.map(e=>[e.id,`${e.ni}-${e.nj}`,`[${e.dofs.join(', ')}]`]))}<h4>Restricciones</h4><p>${r.restricted.map(x=>`<span class="pill">GDL ${x}</span>`).join(' ')||'Ninguna'}</p><h4>Libres</h4><p>${r.free.map(x=>`<span class="pill">GDL ${x}</span>`).join(' ')}</p>`}
 if(activeResultTab==='assembly')html=matrixBlock('Matriz de rigidez global ensamblada K',r.K,r.K.map((_,i)=>'GDL '+i),r.K.map((_,i)=>'GDL '+i));
 if(activeResultTab==='forces')html=`${table(['GDL','F'],r.F.map((v,i)=>[i,`${fmt(v,4)} ${fu}`]))}<p><strong>GDL con cargas declaradas:</strong> ${r.loadDofs.join(', ')}</p>`;
 if(activeResultTab==='free')html=`${matrixBlock('K libres',r.Kff,r.free.map(x=>'GDL '+x),r.free.map(x=>'GDL '+x))}${table(['GDL libre','F'],r.free.map((d,i)=>[d,fmt(r.F[d],4)]))}`;
 if(activeResultTab==='disp')html=table(['Nodo','Ux','Uy','|u|'],r.nodal.map(n=>[n.node,`${fmt(n.ux,6)} ${du}`,`${fmt(n.uy,6)} ${du}`,`${fmt(Math.hypot(n.ux,n.uy),6)} ${du}`]));
 if(activeResultTab==='reactions')html=table(['Nodo','Rx','Ry'],r.nodal.map(n=>[n.node,`${fmt(n.rx,4)} ${fu}`,`${fmt(n.ry,4)} ${fu}`]));
 if(activeResultTab==='internal')html=table(['Elem.','Barra','ε','σ','N','Tipo'],r.elements.map(e=>[e.id,`${e.ni}-${e.nj}`,fmt(e.strain,7),`${fmt(e.stress,5)} ${fu}/${du}²`,`${fmt(e.normal,4)} ${fu}`,`<span class="${e.normal>=0?'positive':'negative'}">${e.type}</span>`]));
 $('#resultContent').innerHTML=html;
}

function draw(){const c=$('#trussCanvas');if(!c)return;const ctx=c.getContext('2d'),W=c.width,H=c.height;ctx.clearRect(0,0,W,H);ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--panel2');ctx.fillRect(0,0,W,H);if(!model.nodes.length)return;const xs=model.nodes.map(n=>+n[1]),ys=model.nodes.map(n=>+n[2]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),pad=70,sx=(W-2*pad)/(maxX-minX||1),sy=(H-2*pad)/(maxY-minY||1),sc=Math.min(sx,sy),cx=(W-(maxX-minX)*sc)/2-minX*sc,cy=(H-(maxY-minY)*sc)/2+maxY*sc;const P=(x,y)=>[cx+x*sc,cy-y*sc],coords=Object.fromEntries(model.nodes.map(n=>[String(n[0]),[+n[1],+n[2]]]));ctx.lineCap='round';
 ctx.strokeStyle='#64748b';ctx.lineWidth=2;for(const [i,j] of model.bars){if(!coords[i]||!coords[j])continue;const a=P(...coords[i]),b=P(...coords[j]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}
 for(const [n,ux,uy] of model.supports){if(!coords[n])continue;const [x,y]=P(...coords[n]);ctx.fillStyle='#f59e0b';ctx.beginPath();ctx.moveTo(x,y+4);ctx.lineTo(x-10,y+18);ctx.lineTo(x+10,y+18);ctx.closePath();ctx.fill();if(ux&&uy){ctx.strokeStyle='#f59e0b';ctx.strokeRect(x-13,y+19,26,4)}else{ctx.beginPath();ctx.arc(x-5,y+22,3,0,Math.PI*2);ctx.arc(x+5,y+22,3,0,Math.PI*2);ctx.fill()}}
 if($('#showLoads')?.checked){for(const [n,fx,fy] of model.loads){if(!coords[n])continue;const mag=Math.hypot(fx,fy);if(!mag)continue;const [x,y]=P(...coords[n]),L=34,dx=fx/mag*L,dy=-fy/mag*L;arrow(ctx,x-dx,y-dy,x,y,'#38bdf8');ctx.fillStyle='#38bdf8';ctx.font='11px Inter';ctx.fillText(`(${fmt(fx,1)}, ${fmt(fy,1)})`,x+7,y-8)}}
 if(result&&$('#showDeformed')?.checked){const scale=Number($('#deformScale').value)||1;for(const e of result.elements){const ci=result.coord[e.ni],cj=result.coord[e.nj],ni=result.nodeNames.indexOf(e.ni),nj=result.nodeNames.indexOf(e.nj),a=P(ci[0]+result.u[2*ni]*scale,ci[1]+result.u[2*ni+1]*scale),b=P(cj[0]+result.u[2*nj]*scale,cj[1]+result.u[2*nj+1]*scale);ctx.strokeStyle=e.normal>=0?'#22c55e':'#ef4444';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}}
 for(const [n,x0,y0] of model.nodes){const [x,y]=P(+x0,+y0);ctx.fillStyle='#e2e8f0';ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();if($('#showLabels')?.checked){ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--text');ctx.font='600 12px Inter';ctx.fillText(String(n),x+7,y-7)}}}
function arrow(ctx,x1,y1,x2,y2,color){const a=Math.atan2(y2-y1,x2-x1),h=9;ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-h*Math.cos(a-Math.PI/6),y2-h*Math.sin(a-Math.PI/6));ctx.lineTo(x2-h*Math.cos(a+Math.PI/6),y2-h*Math.sin(a+Math.PI/6));ctx.closePath();ctx.fill()}

const THEORY=[
 ['1. Idealización de una armadura 2D','Cada nodo posee dos grados de libertad traslacionales: Ux y Uy. Las barras trabajan axialmente y sus uniones se idealizan articuladas. Las cargas se aplican en nodos.','GDL nodo i = [2i, 2i+1]'],
 ['2. Geometría del elemento','Con Δx=xⱼ−xᵢ y Δy=yⱼ−yᵢ se obtiene la longitud L y los cosenos directores c y s, que permiten transformar el comportamiento axial local al sistema global.','L = √(Δx²+Δy²)   c=Δx/L   s=Δy/L'],
 ['3. Rigidez axial local','Para una barra de área A y módulo de elasticidad E, la rigidez axial depende de AE/L. Esta es la relación básica fuerza–desplazamiento del elemento.','kᵉ = (AE/L) [[1,-1],[-1,1]]'],
 ['4. Rigidez global del elemento','La matriz global 4×4 relaciona [uix,uiy,ujx,ujy] con las fuerzas nodales globales equivalentes del elemento.','Kᵉ=(AE/L)[[c²,cs,-c²,-cs],[cs,s²,-cs,-s²],[-c²,-cs,c²,cs],[-cs,-s²,cs,s²]]'],
 ['5. Ensamblaje global','Cada Kᵉ se suma en las filas y columnas de los GDL de sus nodos. Así se forma la matriz K de toda la estructura.','K = Σ ensamblaje(Kᵉ)'],
 ['6. Restricciones y sistema reducido','Los GDL restringidos representan apoyos. El sistema se particiona y se resuelve únicamente en los GDL libres cuando los desplazamientos prescritos son cero.','Kff · Uf = Ff'],
 ['7. Desplazamientos y reacciones','Una vez obtenidos los desplazamientos libres, se reconstruye U completo. Las reacciones se calculan con el equilibrio global.','R = K·U − F'],
 ['8. Deformación, esfuerzo y normal','La deformación axial proviene de proyectar los desplazamientos del elemento sobre su eje. Luego σ=Eε y N=Aσ. El signo de N permite clasificar tracción o compresión.','ε = (1/L)[−c −s c s]uᵉ ; σ=Eε ; N=AEε'],
 ['9. Interpretación de signos','En TOCAScAmE se usa N>0 como tracción, N<0 como compresión y valores próximos a cero como estado neutro.','N > 0 → Tracción   |   N < 0 → Compresión'],
 ['10. Verificación del modelo','Una matriz Kff singular suele indicar un mecanismo, apoyos insuficientes, nodos desconectados, barras de longitud nula o geometría inestable.','det(Kff) ≈ 0 → revisar estabilidad']
];
function renderTheory(){$('#theoryGrid').innerHTML=THEORY.map(([h,p,f])=>`<article class="theory-card"><h3>${h}</h3><p>${p}</p><div class="formula">${f}</div></article>`).join('')}

function exportPDF(){if(!result)return toast('Primero realiza un cálculo');const {jsPDF}=window.jspdf||{};if(!jsPDF)return toast('La librería PDF no está disponible');const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),fu=model.forceUnit,du=model.lengthUnit;doc.setFont('helvetica','bold');doc.setFontSize(19);doc.text('TOCAScAmE · Informe de cálculo matricial',14,16);doc.setFontSize(10);doc.setFont('helvetica','normal');doc.text(`Jhoel Tocas Cercado · Universidad Nacional de Cajamarca · ${new Date().toLocaleString()}`,14,23);doc.text(`Modelo: ${model.name||'Personalizado'} · Nodos: ${model.nodes.length} · Barras: ${model.bars.length} · GDL: ${result.ndof}`,14,29);doc.autoTable({startY:35,head:[['Nodo','X','Y','Ux','Uy','Rx','Ry']],body:result.nodal.map(n=>[n.node,result.coord[n.node][0],result.coord[n.node][1],fmt(n.ux,6),fmt(n.uy,6),fmt(n.rx,4),fmt(n.ry,4)]),styles:{fontSize:7},headStyles:{fillColor:[20,90,140]}});doc.addPage();doc.text('Resultados por elemento',14,16);doc.autoTable({startY:21,head:[['#','Barra','L','A','E','ε','σ','N','Tipo']],body:result.elements.map(e=>[e.id,`${e.ni}-${e.nj}`,fmt(e.L,3),fmt(e.A,3),fmt(e.E,3),fmt(e.strain,7),fmt(e.stress,5),fmt(e.normal,4),e.type]),styles:{fontSize:6.6},headStyles:{fillColor:[20,90,140]}});doc.addPage();doc.text('Matriz de rigidez global K',14,16);doc.autoTable({startY:21,head:[['',...result.K.map((_,i)=>`G${i}`)]],body:result.K.map((r,i)=>[`G${i}`,...r.map(v=>fmt(v,3))]),styles:{fontSize:4.5,cellPadding:1},headStyles:{fillColor:[20,90,140]}});doc.save('TOCAScAmE_informe.pdf')}
function exportExcel(){if(!result)return toast('Primero realiza un cálculo');if(!window.XLSX)return toast('La librería Excel no está disponible');const wb=XLSX.utils.book_new();const add=(name,data)=>XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(data),name);add('Nodos',[['Nodo','X','Y'],...model.nodes]);add('Barras',[['i','j','A','E'],...model.bars]);add('Cargas',[['Nodo','Fx','Fy'],...model.loads]);add('Apoyos',[['Nodo','Restringe Ux','Restringe Uy'],...model.supports]);add('K Global',[['',...result.K.map((_,i)=>`GDL ${i}`)],...result.K.map((r,i)=>[`GDL ${i}`,...r])]);add('K Libre',[['',...result.free.map(i=>`GDL ${i}`)],...result.Kff.map((r,i)=>[`GDL ${result.free[i]}`,...r])]);add('Desplazamientos',[['Nodo','Ux','Uy'],...result.nodal.map(n=>[n.node,n.ux,n.uy])]);add('Reacciones',[['Nodo','Rx','Ry'],...result.nodal.map(n=>[n.node,n.rx,n.ry])]);add('Elementos',[['#','i','j','L','A','E','c','s','epsilon','sigma','N','tipo'],...result.elements.map(e=>[e.id,e.ni,e.nj,e.L,e.A,e.E,e.c,e.s,e.strain,e.stress,e.normal,e.type])]);result.elements.forEach(e=>add(`Ke_${e.id}`,[['Local'],...e.kl,[],['Global'],...e.kg]));XLSX.writeFile(wb,'TOCAScAmE_resultados.xlsx')}
function exportJSON(){syncMeta();const blob=new Blob([JSON.stringify(model,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='TOCAScAmE_modelo.json';a.click();URL.revokeObjectURL(a.href)}

function bind(){
 $('#loadExample1').onclick=()=>{model=clone(EX1);result=null;renderInputs();draw();calc()};$('#loadExample2').onclick=()=>{model=clone(EX2);result=null;renderInputs();draw();calc()};$('#solveBtn').onclick=calc;$('#resetBtn').onclick=()=>{model={name:'Personalizado',lengthUnit:'cm',forceUnit:'kN',scale:100,nodes:[['A',0,0],['B',300,0]],bars:[['A','B',10,20000]],loads:[],supports:[['A',true,true]]};result=null;renderInputs();draw()};$$('[data-add]').forEach(b=>b.onclick=()=>{const k=b.dataset.add;if(k==='node')model.nodes.push([`N${model.nodes.length+1}`,0,0]);if(k==='bar')model.bars.push([model.nodes[0]?.[0]||'A',model.nodes[1]?.[0]||'B',25,2e6]);if(k==='load')model.loads.push([model.nodes[0]?.[0]||'A',0,0]);if(k==='support')model.supports.push([model.nodes[0]?.[0]||'A',false,true]);renderRows();updateStats();draw()});
 ['showLabels','showLoads','showDeformed','deformScale'].forEach(id=>$('#'+id).onchange=draw);$('#fitBtn').onclick=draw;$('#themeToggle').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='light'?'dark':'light';localStorage.setItem('tocascame_theme',document.documentElement.dataset.theme);draw()};
 $$('.nav-item[data-view]').forEach(b=>b.onclick=()=>{$$('.nav-item[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+b.dataset.view).classList.add('active-view');$('#viewTitle').textContent={workspace:'Análisis matricial de armaduras 2D',theory:'Teoría y fundamentos',reports:'Reportes y exportación',about:'Acerca de TOCAScAmE'}[b.dataset.view];$('#sidebar').classList.remove('open')});$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
 ['exportPdfTop','exportPdfBtn'].forEach(id=>$('#'+id).onclick=exportPDF);['exportExcelTop','exportExcelBtn'].forEach(id=>$('#'+id).onclick=exportExcel);$('#exportJsonBtn').onclick=exportJSON;$('#importJson').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{model=JSON.parse(reader.result);result=null;renderInputs();draw();toast('Modelo importado')}catch{toast('JSON no válido')}};reader.readAsText(f)};
}

document.addEventListener('DOMContentLoaded',()=>{document.documentElement.dataset.theme=localStorage.getItem('tocascame_theme')||'dark';initAuth();bind();renderTheory();renderInputs();draw();});